default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: my_glucose_development

test:
  <<: *default
  database: my_glucose_test

production:
  <<: *default
  database: my_glucose_production
  username: my_glucose
  password: <%= ENV["MY_GLUCOSE_DATABASE_PASSWORD"] %>
